import os
os.system('color D')
def menu():
	"""
	Función que limpia la pantalla y muestra nuevamente el menu
	"""
	os.system('cls')
	print ("Selecciona una opción")
	print ("\t1 - Tronox")
	print ("\t2 - Joel")
	print ("\t3 - Brith")
	print ("\t4 - Juan")
	print ("\t5 - Kerrex")
 


while True:
	
    menu()
 
	
    opcionMenu = input("inserta un numero valor >> ")

    if opcionMenu==("1"):
        print ("________________________________________________________________ ")
        print ("_________ _______  _______  _        _______ ")          
        print ("|__   __||  ____ ||  ___  || \    /||  ___  ||\     /| ")
        print ("   | |   | |    ||| |   | ||  \  | || |   | |\ \   / | ")
        print ("   | |   | |____||| |   | ||   \ | || |   | | \ \_/ / ")
        print ("   | |   |    ___|| |   | || |\ \| || |   | |  | _ | ")
        print ("   | |   | |\ \   | |   | || | \   || |   | | / / \ \ ")
        print ("   | |   | | \ \__| |___| || |  \  || |___| |/ /   \ \ ")
        print ("   |_|   |/   \__/|_______||/    \_||_______||/     \| ")
        print ("________________________________________________________________ ")
        print (" DERECHOS DE AUTOR:ECHO POR LINUX3333")
        print ("  ______   _______  ")          
        print (" |  __  \ |  ___  ||\     /| Nombre-->Emanuel Mesa Martinez") 
        print (" | |  \  || |   | || \   / | nombre de su hermano-->Juan Pablo Mesa Martinez")
        print (" | |   | || |   | | \ \_/ /  nombre de su mama-->Cristina")
        print (" | |   | || |   | |  | _ |   Edad-->11") 
        print (" | |   | || |   | | / / \ \  Email-->cristinam32351@gmail.com")
        print (" | |__/  || |___| || /   \ | Nick De Minecraft-->tronox_xm")
        print (" |______/ |_______||/     \| Skype-->live:cristinam32351")
        print ("                             Ultima Ip-->190.8.222.244")
        print("                              facebook de el-->https://www.facebook.com/emmanuel.mesamartinez.1")
        print("                              facebook de su hermano-->https://www.facebook.com/juanpablo.mesa.31508")
        print ("                             facebook de la novia/es (no lo se) de su hermano-->https://www.facebook.com/profile.php?id=100017681250707")
        print ("_________________________________________________________________ ")
        input ("\nPULSA PARA DEJAR DE VER A TRONOX")
    elif opcionMenu==("2"):
        print("_________ _______  _______  _")     
        print("\__    _/|  ___  ||  ____ \| \ ")    
        print("   |  |  | |   | || |    \/| |")    
        print("   |  |  | |   | ||  __|   | |")    
        print("   |  |  | |   | || |      | |")    
        print("|\_|  |  | |___| || |____/\| |____/\ ")
        print("|____/   |_______||_______/|_______/")
        print ("________________________________________________________________ ")
        print (" DERECHOS DE AUTOR:ECHO POR LINUX3333")
        print ("______   _______  ") 
        print("|  __  \ |  ___  ||\     /| Nombre-->Joel Cervantes")
        print("| |  \  || |   | || \   / | Skype-->live:joseratanepe")
        print("| |   | || |   | | \ \_/ /  Edad-->12")
        print("| |   | || |   | |  | _ |   Email-->xxgato13xx@gmail.com")
        print("| |   | || |   | | / / \ \  Nicks De Minecraft -->gato13")
        print("| |__/  || |___| || /   \ | Ultima Ip-->2.151.169.95")
        print("|______/ |_______||/     \| Canal De YT-->https://www.youtube.com/channel/UC3lVH1naDDYJG3K5gB9YPZQ")
        print("                            instagram --> https://www.instagram.com/Toxic_Joelux/")
        print("                            antiguo instagram-->https://www.instagram.com/joel.youtube/")
        print("                            numero de movi --> +34 662 76 43 43")
        print("                            localidad --> Barolucio/Barcelona")
        print("                            instituto --> doctor puigvert")
        print ("________________________________________________________________ ")
        input ("\nPULSA PARA DEJAR DE VER A JOEL")
    elif opcionMenu==("3"):
        print ("___.        .__  __  .__ ")    
        print ("\_ |________|__|/  |_|  |__ ") 
        print ("| \_\ \  | \/  ||  | |   Y  \ ")
        print ("|___  /__|  |__||__| |___|  /")
        print ("    \/                    \/ ")
        print ("________________________________________________________________ ") 
        print (" DERECHOS DE AUTOR:ECHO POR LINUX3333")   
        print ("______   _______  ") 
        print("|  __  \ |  ___  ||\     /| Nombre-->Carlos mario delgado")
        print("| |  \  || |   | || \   / | Edad-->12 ")
        print("| |   | || |   | | \ \_/ /  Email-->carlosmariodelg@gmail.com")
        print("| |   | || |   | |  | _ |   Nick De Minecraft-->brithspringtrap")
        print("| |   | || |   | | / / \ \  Skype-->live:carlosmariodelg ")
        print("| |__/  || |___| || /   \ | Ultima Ip-->46.25.102.221 (pasada)")
        print("|______/ |_______||/     \| Instagram-->https://www.instagram.com/_cxrlos_d.c/")
        print ("________________________________________________________________ ")
        input ("\nPULSA PARA DEJAR DE VER A BRITH")
    elif opcionMenu==("4"):
        print ("     ____.")                    
        print ("    |    |__ _______    ____  ")
        print ("    |    |  |  \__  \  /    \ ")
        print ("/\__|    |  |  // __ \|   |  \ ")
        print ("\________|____//____  /___|  / ")
        print ("                    \/     \/ ") 
        print ("________________________________________________________________ ")
        print (" DERECHOS DE AUTOR:ECHO POR LINUX3333")
        print ("______   _______  ") 
        print("|  __  \ |  ___  ||\     /| Nombre-->Juan Balboa")
        print("| |  \  || |   | || \   / | Skype-->live:80a6a5f833e7e50e")
        print("| |   | || |   | | \ \_/ /  Edad-->12")
        print("| |   | || |   | |  | _ |   numero de movil --> +34 640 07 86 26")
        print("| |   | || |   | | / / \ \  instagram --> https://www.instagram.com/juan_oficial72/")
        print("| |__/  || |___| || /   \ | Nicks De Minecraft -->Ju4N")
        print("|______/ |_______||/     \| Ultima Ip-->37.15.95.28")
        print("                            localidad --> Barolucio/Barcelona")
        print("                            instituto --> doctor puigvert")
        print ("________________________________________________________________ ")
        input ("\nPULSA PARA DEJAR DE VER A JUAN")
    elif opcionMenu==("5"):
        print (" _        _______  _______  _______  _______ ")         
        print ("| \    /\|  ____ \|  ____ ||  ____ ||  ____ \|\     /| ")
        print ("|  \  / /| |    \/| |    ||| |    ||| |    \/| \   / | ")
        print ("|  |_/ / | |__    | |____||| |____||| |__     \ |_| / ")
        print ("|   _ |  |  __|   |     __||     __||  __|     | _ | ") 
        print ("|  | \ \ | |      | |\ |   | |\ |   | |       / | | \ ")
        print ("|  /  \ \| |____/\| | \ \__| | \ \__| |____/\/ /   \ | ")
        print ("|_/    \/|_______/|/   \__/|/   \__/|_______/|/     \| ")                                                     
        print("________________________________________________________________ ")
        print (" DERECHOS DE AUTOR:ECHO POR LINUX3333")
        print (" ______   _______  ") 
        print("|  __  \ |  ___  ||\     /| Nombre-->Keyvinth")
        print("| |  \  || |   | || \   / | Edad-->14")
        print("| |   | || |   | | \ \_/ /  Email-->kerrex12@gmail.com")
        print("| |   | || |   | |  | _ |   Nick De Minecraft-->kerrex21")
        print("| |   | || |   | | / / \ \  Skype-->live:kerrex12")
        print("| |__/  || |___| || /   \ | Ultima Ip-->185.88.203.90")
        print("|______/ |_______||/     \| Calan De yt-->https://www.youtube.com/channel/UCZEONfjDIg3h059tymn9RCg ")
        print("                            fecha de Su Nacimiento-->27/12/2004")
        print("________________________________________________________________ ")
        input ("\nPULSA PARA DEJAR DE VER A KERREX")
    else:
        print("no has pulsado ninguna opcion correcta")
        input("\nPulsa enter para seguir viendo")
